# Generated by Django 6.0.7 on 2026-07-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Perfume')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('notas_saida', models.CharField(max_length=200, verbose_name='Notas de Saida (Topo)')),
                ('notas_coracao', models.CharField(max_length=200, verbose_name='Notas de Coracao (Corpo)')),
                ('notas_fundo', models.CharField(max_length=200, verbose_name='Notas de Fundo (Base)')),
                ('estoque', models.IntegerField(default=10, verbose_name='Quantidade em Estoque')),
            ],
        ),
    ]
