# Generated by Django 6.0.7 on 2026-07-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='Imagem do Perfume'),
        ),
    ]
