# Generated by Django 6.0.7 on 2026-07-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_genero_marca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ex: Promoção de Dia dos Pais", max_length=100
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Até 30% OFF em fragrâncias marcantes",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True, help_text="Marque para exibir no site"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="perfume",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="perfume",
            name="criado_em",
        ),
        migrations.AlterField(
            model_name="perfume",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="estoque",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="genero",
            field=models.CharField(
                choices=[
                    ("masculino", "Masculino"),
                    ("feminino", "Feminino"),
                    ("unissex", "Unissex"),
                ],
                default="unissex",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="perfumes/"),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="marca",
            field=models.CharField(
                choices=[
                    ("lattafa", "Lattafa"),
                    ("armaf", "Armaf"),
                    ("afnan", "Afnan"),
                    ("maison-alhambra", "Maison Alhambra"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="notas_coracao",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="notas_fundo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="notas_saida",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="CampanhaPerfume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "campanha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.campanha"
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.perfume"
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.AddField(
            model_name="campanha",
            name="perfumes",
            field=models.ManyToManyField(
                blank=True,
                related_name="campanhas",
                through="core.CampanhaPerfume",
                to="core.perfume",
            ),
        ),
    ]
