from django.shortcuts import render
from django.db import connection
from django.db.utils import ProgrammingError, OperationalError
from .models import Perfume, Campanha

def limpar_tabelas_antigas_e_garantir_novas():
    """Remove a tabela intermediária antiga para evitar erro de Foreign Key ao apagar perfumes."""
    try:
        with connection.cursor() as cursor:
            # 1. Garante a tabela nova
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS core_campanhaperfume (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ordem integer NOT NULL DEFAULT 0,
                    campanha_id bigint NOT NULL REFERENCES core_campanha(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    perfume_id bigint NOT NULL REFERENCES core_perfume(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                );
            """)
            # 2. Apaga a tabela antiga que travava a eliminação dos perfumes
            cursor.execute("DROP TABLE IF EXISTS core_campanha_perfumes CASCADE;")
    except Exception as e:
        print(f"Aviso no banco: {e}")


def home(request):
    # Executa a limpeza da tabela antiga e criação da nova
    limpar_tabelas_antigas_e_garantir_novas()

    # Traz os perfumes cadastrados mais recentes primeiro (máximo 10)
    lancamentos = Perfume.objects.all().order_by('-id')[:10]
    
    # Busca a campanha ativa
    try:
        campanha_ativa = Campanha.objects.filter(ativa=True).first()
    except (ProgrammingError, OperationalError):
        campanha_ativa = None

    context = {
        'lancamentos': lancamentos,
        'campanha_ativa': campanha_ativa,
    }
    return render(request, 'core/home.html', context)


def colecao(request):
    # Ordena do mais recente para o mais antigo na coleção
    perfumes = Perfume.objects.all().order_by('-id')
    
    genero = request.GET.get('genero')
    marca = request.GET.get('marca')

    if genero:
        perfumes = perfumes.filter(genero=genero)
    if marca:
        perfumes = perfumes.filter(marca=marca)

    context = {
        'perfumes': perfumes,
        'genero_selecionado': genero,
        'marca_selecionada': marca,
    }
    return render(request, 'core/colecao.html', context)