from django.shortcuts import render
from django.db import connection
from django.db.utils import ProgrammingError, OperationalError
from .models import Perfume, Campanha

# Força a criação da tabela intermediária se ela ainda não existir no PostgreSQL
try:
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS core_campanhaperfume (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ordem integer NOT NULL DEFAULT 0,
                campanha_id bigint NOT NULL REFERENCES core_campanha(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                perfume_id bigint NOT NULL REFERENCES core_perfume(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
        """)
except Exception:
    pass


def home(request):
    # Traz os perfumes cadastrados mais recentes primeiro (máximo 10)
    lancamentos = Perfume.objects.all().order_by('-id')[:10]
    
    # Busca a campanha ativa
    try:
        campanha_ativa = Campanha.objects.filter(ativa=True).first()
    except (ProgrammingError, OperationalError):
        campanha_ativa = None

    context = {
        'lancamentos': lancamentos,
        'campanha_ativa': campanha_ativa,
    }
    return render(request, 'core/home.html', context)


def colecao(request):
    # Ordena do mais recente para o mais antigo na coleção
    perfumes = Perfume.objects.all().order_by('-id')
    
    genero = request.GET.get('genero')
    marca = request.GET.get('marca')

    if genero:
        perfumes = perfumes.filter(genero=genero)
    if marca:
        perfumes = perfumes.filter(marca=marca)

    context = {
        'perfumes': perfumes,
        'genero_selecionado': genero,
        'marca_selecionada': marca,
    }
    return render(request, 'core/colecao.html', context)